---
- name: Setup Remote Servers with Apache configured
  hosts: webservers
  become: true
  #remote_user: ubuntu
  vars_files:
    - ./vars/variables.yml

  tasks:
  # Updating the apt repos
  - name: Update and upgrade apt packages
    apt:
      update_cache: yes
      autoclean: yes
      autoremove: yes
      upgrade: yes
    
  
  # Setting the server's time to Lagos
  - name: set timezone to Africa/lagos
    timezone:
      name: Africa/Lagos
    

  # Installing required apache2
  - name: Install Packages
    package:
      name: "{{ packages }}"
      state: latest

  - name: print hostname on server
    shell: echo "<h1>Server name - $(hostname -f)</h1>" > /var/www/html/index.html  
  
  - name: restart the apache2 service
    service:
      name: apache2
      state: restarted
